spring:
  application:
    name: Library-Management-System-Backend

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/Library_Management?createDatabaseIfNotExist=true
    username: root
    password: "Parthav@2901"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true